// <auto-generated/>
// 由 SilkEngine.SourceGen.ComponentSerializerGenerator 生成

partial class SampleStj
{
    public override void WriteTo(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        node.SetRaw("Tags", Tags == null ? null : global::System.Text.Json.JsonSerializer.SerializeToNode(Tags));
        node.SetRaw("Stamp", global::System.Text.Json.JsonSerializer.SerializeToNode(Stamp));
    }

    public override void ReadFrom(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        var __rawTags = node.GetRaw("Tags");
        if (__rawTags != null)
        {
            try { Tags = global::System.Text.Json.JsonSerializer.Deserialize<global::System.String[]>(__rawTags); }
            catch (global::System.Text.Json.JsonException) { }
        }
        var __rawStamp = node.GetRaw("Stamp");
        if (__rawStamp != null)
        {
            try { Stamp = global::System.Text.Json.JsonSerializer.Deserialize<global::System.DateTime>(__rawStamp); }
            catch (global::System.Text.Json.JsonException) { }
        }
    }
}
