// <auto-generated/>
// 由 SilkEngine.SourceGen.ComponentSerializerGenerator 生成

partial class SampleWhitelist
{
    public override void WriteTo(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        node.SetFloat("Speed", Speed);
        node.SetBool("Lit", Lit);
        node.SetString("Label", Label);
        node.SetString("Id", Id == default ? null : Id.ToString());
        node.SetVector3("Offset", Offset);
        node.SetQuaternion("Rotation", Rotation);
    }

    public override void ReadFrom(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        if (node.ContainsKey("Speed")) Speed = node.GetFloat("Speed");
        if (node.ContainsKey("Lit")) Lit = node.GetBool("Lit");
        if (node.ContainsKey("Label")) Label = node.GetString("Label");
        if (node.ContainsKey("Id"))
        {
            var __v = node.GetString("Id");
            Id = __v is null || !global::System.Guid.TryParse(__v, out var __g) ? default : __g;
        }
        if (node.ContainsKey("Offset")) Offset = node.GetVector3("Offset");
        if (node.ContainsKey("Rotation")) Rotation = node.GetQuaternion("Rotation");
    }
}
