// <auto-generated/>
// 由 SilkEngine.SourceGen.ComponentSerializerGenerator 生成

partial class SampleAssets
{
    public override void WriteTo(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        global::SilkEngine.Scene.Serialization.AssetRefCodec.Write(node, "Shader", Shader);
    }

    public override void ReadFrom(global::SilkEngine.Scene.Serialization.SerializedNode node)
    {
        Shader = global::SilkEngine.Scene.Serialization.AssetRefCodec.Read<global::SilkEngine.Render.Shader>(node, "Shader");
    }
}
