// <auto-generated/>
// 由 SilkEngine.SourceGen.ComponentSerializerGenerator 生成

partial class SampleOuter
{
    public override void WriteTo(global::SilkEngine.Core.Assets.Serialization.SerializedNode node)
    {
        node.SetFloat("Power", Power);
        if (Stats != null) node.SetFloat("Stats_HP", Stats.HP);
    }

    public override void ReadFrom(global::SilkEngine.Core.Assets.Serialization.SerializedNode node)
    {
        if (node.ContainsKey("Power")) Power = node.GetFloat("Power");
        if (node.ContainsKey("Stats_HP"))
        {
            Stats ??= new global::SampleStats();
            Stats.HP = node.GetFloat("Stats_HP");
        }
    }
}
