using Microsoft.CodeAnalysis;
using Xunit;

namespace SilkEngine.SourceGen.Tests;

public class ServiceRegistrationGeneratorTests
{
    private const string Snippet = """
        using SilkEngine.Core;

        [Service(0)]
        public class FirstService { }

        [Service]
        public class SecondService { }

        [Service(2, "Named")]
        public class ThirdService { }
        """;

    private const string ExpectedBootstrap = """
        // <auto-generated/>
        // 由 SilkEngine.SourceGen.ServiceRegistrationGenerator 生成

        internal static class __ServiceBootstrap
        {
            [global::System.Runtime.CompilerServices.ModuleInitializer]
            internal static void RegisterServices()
            {
                global::SilkEngine.Core.Services.Register<global::FirstService>(new global::FirstService());
                global::SilkEngine.Core.Services.Register<global::SecondService>(new global::SecondService());
                global::SilkEngine.Core.Services.Register<global::ThirdService>(new global::ThirdService(), name: "Named");
            }
        }
        """;

    [Fact]
    public void ServiceMarkedClasses_GenerateBootstrap_SortedByPriority()
    {
        // 生成器仅接受 SilkEngine 程序集（SERV001），此处显式以引擎程序集名编译
        var (generated, diags) = ServiceHarness.Run(Snippet, assemblyName: "SilkEngine");
        Assert.Empty(diags.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.Equal(ServiceHarness.Normalize(ExpectedBootstrap),
            ServiceHarness.Normalize(Assert.Single(generated, g => g.Contains("__ServiceBootstrap"))));
    }

    [Fact]
    public void NoServiceAttribute_GeneratesNothing()
    {
        var (generated, _) = ServiceHarness.Run("public class Plain { }");
        Assert.Empty(generated);
    }

    [Fact]
    public void ExternalAssembly_ErrorsServ001()
    {
        var (_, diags) = ServiceHarness.Run("""
            using SilkEngine.Core;
            [Service]
            public class Bad { }
            """, assemblyName: "UserApp");
        Assert.Contains(diags, d => d.Id == "SERV001" && d.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void AbstractOrParameterized_ErrorsServ002()
    {
        var (_, diags) = ServiceHarness.Run("""
            using SilkEngine.Core;
            [Service]
            public abstract class AbstractBad { }
            [Service]
            public class CtorBad { public CtorBad(int x) { } }
            """, assemblyName: "SilkEngine");
        Assert.Contains(diags, d => d.Id == "SERV002" && d.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void NonPublicCtor_ErrorsServ002_WithVisibility()
    {
        var (_, diags) = ServiceHarness.Run("""
            using SilkEngine.Core;
            [Service]
            public class PrivateCtorBad { private PrivateCtorBad() { } }
            """, assemblyName: "SilkEngine");
        var d = Assert.Single(diags, x => x.Id == "SERV002" && x.Severity == DiagnosticSeverity.Error);
        Assert.Contains("PrivateCtorBad", d.GetMessage());
        Assert.Contains("Private", d.GetMessage());
    }

    [Fact]
    public void NameWithQuotesAndNewlines_EscapedInGeneratedCode()
    {
        const string snippet = """
            using SilkEngine.Core;
            [Service(0, "say \"hi\" back\\slash\nnext")]
            public class EscapedName { }
            """;
        var (generated, diags) = ServiceHarness.Run(snippet, assemblyName: "SilkEngine");
        Assert.Empty(diags.Where(d => d.Severity == DiagnosticSeverity.Error));
        var bootstrap = Assert.Single(generated, g => g.Contains("__ServiceBootstrap"));
        Assert.Contains("""
            name: "say \"hi\" back\\slash\nnext"
            """, bootstrap);
        Assert.Empty(ServiceHarness.RunCompileCheck(snippet + "\n" + ServicesStub, assemblyName: "SilkEngine"));
    }

    [Fact]
    public void GeneratedCode_Recompiles_WithoutErrors()
    {
        // 生成代码调用 internal Services.Register —— 仅在产物实际编译的上下文（引擎程序集）中可解析；
        // 同编译 stub 遮蔽外部 SilkEngine.dll 的 internal Services，模拟该场景
        Assert.Empty(ServiceHarness.RunCompileCheck(Snippet + "\n" + ServicesStub, assemblyName: "SilkEngine"));
    }

    /// <summary>模拟引擎程序集内可见的 Services 注册面（internal，与 SilkEngine.Core.Services 同形）。</summary>
    private const string ServicesStub = """
        namespace SilkEngine.Core
        {
            internal static class Services
            {
                public static void Register<T>(T service, string? name = null) where T : class { }
            }
        }
        """;
}
