<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>SilkEngine.Tests</AssemblyName>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\SilkEngine.Host\SilkEngine.Host.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Runtime\SilkEngine.Runtime.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Assets\SilkEngine.Assets.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Scene\SilkEngine.Scene.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Rendering\SilkEngine.Rendering.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Rendering.Abstraction\SilkEngine.Rendering.Abstraction.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Rendering.Backend\SilkEngine.Rendering.Backend.csproj" />
      <ProjectReference Include="..\..\src\SilkEngine.Rendering.OpenGL\SilkEngine.Rendering.OpenGL.csproj" />
      <ProjectReference Include="..\..\src\Sandbox\Sandbox.csproj" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\SilkEngine.SourceGen\SilkEngine.SourceGen.csproj"
                        OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
      <None Include="..\..\src\Sandbox\Assets\**"
            Link="Assets\%(RecursiveDir)%(Filename)%(Extension)"
            CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
