using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SilkEngine.SourceGen;

/// <summary>
/// 序列化源生成器（骨架版）：对顶层 Component 子类生成空 partial，验证项目引用→生成→编译流水线。
/// 跳过规则：抽象类、非 Component 子类、嵌套类型（文档化限制）、自身声明 ReadFrom/WriteTo 的类型（用户手动接管）。
/// 字段级 WriteTo/ReadFrom 生成由任务 4 实现。
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ComponentSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var components = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ComponentInfo.TryCreate(ctx, ct))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(components, static (spc, infos) =>
        {
            foreach (var info in infos)
            {
                if (info is not { } i)
                    continue;
                spc.AddSource(i.HintName, SourceText.From(i.EmitSkeleton(), Encoding.UTF8));
            }
        });
    }

    private sealed class ComponentInfo
    {
        public INamedTypeSymbol Symbol { get; }

        private ComponentInfo(INamedTypeSymbol symbol) => Symbol = symbol;

        public string HintName => Symbol.ToDisplayString()
            .Replace("global::", "").Replace('.', '_') + ".g.cs";

        public static ComponentInfo? TryCreate(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax)
                return null;
            if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol)
                return null;
            if (symbol.IsAbstract || symbol.IsStatic)
                return null;
            if (symbol.ContainingType is not null)
                return null;   // 嵌套类型不生成（文档化限制，见附录规则 R0）
            var component = ctx.SemanticModel.Compilation.GetTypeByMetadataName(GenConstants.Component);
            if (component is null || !IsDerivedFrom(symbol, component))
                return null;
            if (symbol.GetMembers("ReadFrom").Length > 0 || symbol.GetMembers("WriteTo").Length > 0)
                return null;   // 用户手动接管，生成器跳过
            return new ComponentInfo(symbol);
        }

        private static bool IsDerivedFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
        {
            for (var t = symbol.BaseType; t is not null; t = t.BaseType)
                if (SymbolEqualityComparer.Default.Equals(t, baseType))
                    return true;
            return false;
        }

        public string EmitSkeleton()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 由 SilkEngine.SourceGen.ComponentSerializerGenerator 生成");
            sb.AppendLine();
            var ns = Symbol.ContainingNamespace;
            if (!ns.IsGlobalNamespace)
            {
                sb.Append("namespace ").Append(ns.ToDisplayString()).AppendLine(";");
                sb.AppendLine();
            }
            sb.Append("partial class ").Append(Symbol.Name).AppendLine();
            sb.AppendLine("{");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
