using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace SilkEngine.SourceGen;

/// <summary>
/// 服务自动注册生成器：扫描 [Service] 标记的类，按 (Priority 升序, 类型全名升序) 生成
/// __ServiceBootstrap（[module: ModuleInitializer]）→ Services.Register&lt;T&gt;(new T(), name)。
/// 仅引擎程序集可用（SERV001）；非抽象且具无参构造（SERV002）。
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ServiceRegistrationGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Serv001 = new(
        id: "SERV001",
        title: "Service 禁止外部使用",
        messageFormat: "特性 [Service] 仅允许在 SilkEngine 程序集内使用（当前程序集 '{0}'）",
        category: "SilkEngine.Core",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor Serv002 = new(
        id: "SERV002",
        title: "Service 类型必须为非抽象且具公共无参构造",
        messageFormat: "类型 '{0}' 不能标记 [Service]（必须是引擎程序集内的非抽象类且具有公共无参构造，实际：{1}）",
        category: "SilkEngine.Core",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var marked = context.SyntaxProvider.ForAttributeWithMetadataName(
            "SilkEngine.Core.ServiceAttribute",
            static (_, _) => true,
            static (ctx, ct) =>
            {
                var symbol = ctx.TargetSymbol as INamedTypeSymbol;
                if (symbol is null)
                    return null;
                int priority = 0;
                string? name = null;
                foreach (var attr in symbol.GetAttributes())
                {
                    if (attr.AttributeClass?.ToDisplayString() != "SilkEngine.Core.ServiceAttribute")
                        continue;
                    foreach (var arg in attr.ConstructorArguments)
                    {
                        if (arg.Value is int p)
                            priority = p;
                        else if (arg.Value is string s)
                            name = s;
                    }
                }
                return new ServiceInfo(symbol, priority, name);
            })
            .Where(static s => s is not null)
            .Collect();

        context.RegisterSourceOutput(marked, static (spc, infos) =>
        {
            var list = infos.Where(i => i is not null).Cast<ServiceInfo>()
                .OrderBy(i => i.Priority)
                .ThenBy(i => i.Symbol.ToDisplayString(), StringComparer.Ordinal)
                .ToList();
            foreach (var info in list)
            {
                var loc = info.Symbol.Locations.FirstOrDefault() ?? Location.None;
                if (info.Symbol.ContainingAssembly?.Name != "SilkEngine")
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Serv001, loc, info.Symbol.ContainingAssembly?.Name ?? "?"));
                    continue;
                }
                if (info.Symbol.IsAbstract
                    || !HasPublicParameterlessCtor(info.Symbol))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Serv002, loc, info.Symbol.Name, CtorVisibilityDetail(info.Symbol)));
                    continue;
                }
            }
            var valid = list
                .Where(i => i.Symbol.ContainingAssembly?.Name == "SilkEngine"
                    && !i.Symbol.IsAbstract
                    && HasPublicParameterlessCtor(i.Symbol))
                .ToList();
            if (valid.Count == 0)
                return;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 由 SilkEngine.SourceGen.ServiceRegistrationGenerator 生成");
            sb.AppendLine();
            sb.AppendLine("internal static class __ServiceBootstrap");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("    internal static void RegisterServices()");
            sb.AppendLine("    {");
            foreach (var info in valid)
            {
                var full = info.Symbol.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers));
                var nameArg = info.Name is null ? "" : ", name: " + SymbolDisplay.FormatLiteral(info.Name, quote: true);
                sb.AppendLine("        global::SilkEngine.Core.Services.Register<" + full
                    + ">(new " + full + "()" + nameArg + ");");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("__ServiceBootstrap.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    /// <summary>公共无参构造判定（生成的 new T() 需同程序集可解析；约定仅接受 public 可见性）。</summary>
    private static bool HasPublicParameterlessCtor(INamedTypeSymbol symbol) =>
        symbol.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

    /// <summary>SERV002 可见性明细（供诊断消息展示类型实际状态）。</summary>
    private static string CtorVisibilityDetail(INamedTypeSymbol symbol)
    {
        if (symbol.IsAbstract)
            return "抽象类型";
        var ctor = symbol.InstanceConstructors.FirstOrDefault(c => c.Parameters.Length == 0);
        return ctor is null ? "无无参构造" : ctor.DeclaredAccessibility.ToString();
    }

    private sealed record ServiceInfo(INamedTypeSymbol Symbol, int Priority, string? Name);
}
